[platformio]
extra_configs =
  platformio_override.ini

[env]
platform = espressif8266
board = esp12e
framework = arduino
lib_deps =
  adafruit/Adafruit ST7735 and ST7789 Library @ ^1.11.0
  https://github.com/hmueller01/pubsubclient3.git
  bblanchon/ArduinoJson @ ^7.4.1

[env:default]
upload_protocol = esptool
